version: "0.2"
ignorePaths:
  - ./tests/sample-response.json
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - custom-dictionary
words: []
ignoreWords: []
import: []
